common:
  project: CdkATT
  removalPolicy: retain
  logRetentionDays: 90
  tracingEnabled: false
  tags:
    owner: Al

stages:
  prd:
  stg:
  dev:
    tracingEnabled: true
    removalPolicy: destroy
    logRetentionDays: 7

be:
  common:
    apiResourceName: api
    monitorRegion: eu-central-1
    regions:
      - eu-central-1
      - us-east-1
  stages:
    dev:
      regions:
        - eu-central-1

deployer:
  common:
    githubRepo: tsertkov/cdk-all-the-things
    githubOidcArnCfnOutput: GithubOidcArn
    regions:
      - eu-central-1
  stages:
    dev:
      noApprovalDeploy: true
    stg:
      promotionSrc: dev
    prd:
      promotionSrc: stg

monitor:
  common:
    regions:
      - eu-central-1
