project: CdkATT

apps:
  - deployer-glb
  - monitor-glb
  - monitor
  - be
  - fe

secrets:
  keyRegion: eu-central-1

common:
  removalPolicy: retain
  logRetentionDays: 90
  tracingEnabled: false
  tags:
    owner: Al

stages:
  prd:
  stg:
  dev:
    tracingEnabled: true
    removalPolicy: destroy
    logRetentionDays: 7

deployer-glb:
  common:
    githubRepo: tsertkov/cdk-all-the-things
    githubOidcArnCfnOutput: GithubOidcArn
    ecrMaxImageCount: 30
    regions:
      - eu-central-1
  stages:
    dev:
      noApprovalDeploy: true
      ecrMaxImageCount: 10
    stg:
      promotionSrc: dev
    prd:
      promotionSrc: stg

monitor-glb:
  common:
    logsBucketName: logs-eeb9aW
    regions:
      - eu-central-1

monitor:
  common:
    logsBucketName: logs-eeb9aW
    globalRegion: eu-central-1
    regions:
      - eu-central-1
      - us-east-1
  stages:
    dev:
      regions:
        - eu-central-1

be:
  common:
    apiResourceName: api
    monitorRegion: eu-central-1
    regions:
      - eu-central-1
      - us-east-1
  stages:
    dev:
      regions:
        - eu-central-1

fe:
  common:
    regions:
      - eu-central-1
