common:
  project: CdkATT
  removalPolicy: retain
  logRetentionDays: 90
  tracingEnabled: false
  tags:
    owner: Al

apps:
  - deployer-gl
  - monitor-gl
  - monitor
  - be

stages:
  prd:
  stg:
  dev:
    tracingEnabled: true
    removalPolicy: destroy
    logRetentionDays: 7

deployer-gl:
  common:
    githubRepo: tsertkov/cdk-all-the-things
    githubOidcArnCfnOutput: GithubOidcArn
    regions:
      - eu-central-1
  stages:
    dev:
      noApprovalDeploy: true
    stg:
      promotionSrc: dev
    prd:
      promotionSrc: stg

monitor-gl:
  common:
    logsBucketName: logs-eeb9aW
    regions:
      - eu-central-1

monitor:
  common:
    logsBucketName: logs-eeb9aW
    globalRegion: eu-central-1
    regions:
      - eu-central-1
      - us-east-1
  stages:
    dev:
      regions:
        - eu-central-1
be:
  common:
    apiResourceName: api
    monitorRegion: eu-central-1
    regions:
      - eu-central-1
      - us-east-1
  stages:
    dev:
      regions:
        - eu-central-1
