monitor-glb:
    common:
        hec: ENC[AES256_GCM,data:PgoGLtfX,iv:VK8t8ncnB1kEtP2yrexjAKlhC99+CLZRCDphqChza0s=,tag:q/DJra4CRUB/YJmrkODkhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15e87ct5alw9cf288p0snvnu635g380kh4wufhxatmvefe00aw33sxhu2pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBienVSVnZabTkrZ3VleDRQ
            cStHR0U2MzBoUTZYdlNSS2hSN21BZ2NRd2swClJzQXVIRjBLMjlFd2o0a3RWUkFn
            RXFFTlYvN2tmRzNtTTltT1hsbFg2d0UKLS0tIHN6LzNlM08wOFphbTBSZG44S1Ru
            VEdnRFhzMVI5QUY0bS9MWnczM3ZmRUEKKJmO0QVKCCE3G/7p63U36tDjZZuAN9lY
            qCyclnSLMAfSmF26Yb1dNpbZcC2qSPMR2TlGOf8G7QOEu/tuaVXGPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-28T21:39:51Z"
    mac: ENC[AES256_GCM,data:NFrweElw+w8AI+7xQjk+vblZZFDS06uMy7bA3IA4HqxmN6gWbaExqlj4YkN9qxTSHIUzjyncEfQXRiJmG09Yk67cGBvUPmeZVi6c4Wf72yuG7hLOqBpW7aP2qPvBZ0Y8MFVPAq5U1nB4Wh7m93nIijU6CF+pJNZq5Mhv/oOIiP8=,iv:q0oIPq6w+U3Rg2UkJhgMmglSlKdyvpMn0rCLfMM5Br4=,tag:MsV+SBUK+Dy0oUBxMPtYTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
