monitor-glb:
    common:
        hec: ENC[AES256_GCM,data:eUvxYliU,iv:V0VehcJ4shj8YBgBJpwshryJ1vscQfR5Gy+LvcM8nAc=,tag:9xd2E/p6B+5snP09gutxLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5mdpslxzcm4e5qr82p53tmy6e04ftru80saemjxq9dpvpyqnggqrdlwc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYUR3Q251Tk9jbDVsOU5N
            b2lDamJsK3M1SENGTUZ1NmIxbXNhNDFrTkdNCmxsUndSN1I4TE50VXpqcG56TkMz
            bllFb3ArUjdGd21rWVFpSlhOb1dTUmcKLS0tIDJXaXdPd3VsOVcwSVB0bTRjcmxo
            emhaVzJYQytSQ1l4d0duOGxUWThJYXcKM7ncfwCxRgQNU4jaHiuNdfoiGPgM2IiZ
            QI7Ve9YYhlRqItNeyPJND9OeK02R0WpJZCtoErrntoiywYvJcYx6sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-28T21:30:33Z"
    mac: ENC[AES256_GCM,data:OF9mr8QfLWBREklqN9yz0IOoIdH1ekozMxzA0zZoJHaoCWevrk4amnkvwhapz5j8Ln0NvZc4l5dLLiCff86lIWouuWL+C+Ue7Uq0Jr9lgopiiJCJsnJwI2af+7zpqjf7nhC1v4UGSxKYrRSQH2zfuGUG2Cw/q9tqMD7uSDqdo2M=,iv:1fA+MYXcUx/+QkUG09YRF6xefVK+1oEMnn6WdVZFWvo=,tag:zwAv70xwatw3lTd7OTVDzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
