monitor-glb:
    common:
        hec: ENC[AES256_GCM,data:F1J0JlBk,iv:17+ddGM09kzor3OYbFGq3h6m1cdDwN4rHfE6VxrxRNw=,tag:JlQ6vrJJ3uKO+c9scQu9oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yjq56qnkygxs0n3l6madxg74zfp6cfeq5fj38g0m96f02f2zjpkq2f7egr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dU9GcG56dU5CRUJaVk5Y
            QjlaSWorRy96N3lNSkhOaEI4SjZsL1d2WUNZClZlekdYaENYeWwwdEpPU0tzRXcy
            QVdKZTVUTWtZU0gvd3lWQ1o2bmhIeEkKLS0tIFFCZFc3bTAwWlphMG9kTy81NWcw
            RUh3ZFRoeVFSOHI2VkVqWlI5UC9oYmMK9LRyOwOUKh9d2vwqSdhk7c/+Koksqccm
            HPZkquCxL/VRRFcT4QQviC/CeVtijx9UgP1ICOGN4842n8S24ONPFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-28T21:42:58Z"
    mac: ENC[AES256_GCM,data:zELXN0+Sh47kDZegZSYtUhfxQ24i2FaLlVMQLhC1LKar1XkoZdqXzTA7jkFBLTKpbA/6HCFwTc2QDxTtErY1sM7fud8dApLwARWsNDzKg3tSGCjPzJhwfn3OWsgkhkWnKqDfCfkYWByuBtJHtAyodJ38piykFujmkJozB1zfNS0=,iv:1dhKmbgUlZTYOxkWBzph1hew8YNXOBTbFDgP2oNQ45c=,tag:zFVwFO4rxMpVY4ZP4LkTwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
