common:
    account: ENC[AES256_GCM,data:c9yq6RxC/kRUFGvt,iv:LhaJTu0qGY6L6/EbvHQN3uu8xCYsdQzE9P1h8zjMHYA=,tag:TZ1PpOh34e0sXXNN3FrpJg==,type:str]
stages:
    prd:
        account: ENC[AES256_GCM,data:UFRPs6nxK3cg3zW+,iv:Cd/RVJek6W+MPTzsOXD6SlEVP4bcf/dnlgPokRGcRIQ=,tag:jK/kQujmJ6sTXTm+eXAeRw==,type:str]
monitor-glb:
    common:
        hec: ENC[AES256_GCM,data:k4Of8DhM,iv:8vKreGMgGjU5n+4+vT3y0LzEj/yn+i37++y9E/zKZtg=,tag:5wgFXdGVAYjaSAF2L/FoTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15e87ct5alw9cf288p0snvnu635g380kh4wufhxatmvefe00aw33sxhu2pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cnpTd2pZTWlXeVlOeDVW
            QnFzNEF4eVF2TnVrSGV6eUNCbW5EUmdxbldvCis2aTVxQXRlb1h6SXU1OUFFVzhj
            b3pvU2tMdnJHeE9meThRcTM3Ylo3ZTgKLS0tIFlqb0pwZVFvL25nNmp1aDIxUkZJ
            SURVNGpJWU9xWGw5Z1JmblduWk5ValkKsjMk9/4lEEJVHaj8UlNwQW9O0lPHoneO
            jttb9oeg6DO1xIeRzrRQ5UmVf6axThel9UjUE+6MH8TllqcI2/q6Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-29T07:44:21Z"
    mac: ENC[AES256_GCM,data:pAb6UQ9u+5R84ldsCBnYYOO5VF83t2HM7HBeoWnohp8QvnsYKlulS2onIziJpRo20fEYvug/UoITrgVURPmlNSTbQpXYMbCi22K1Naonh9yRhNrpJiQg0Dx2Gk+8KMRkfbM+ej33Lmh9tO4vI4B8Ptl/d/QA9/tS1V3uPjg3Ak8=,iv:kQ7r8nz/6MBPf96NanYB28tkqYgrd9uFPACUHH08Dr4=,tag:YkOss/2n9V2Js3onazR9Aw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
