name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
  push:
    branches:
      - master
      - release/*
    paths-ignore:
      - README.md

jobs:
  version:
    uses: ./.github/workflows/gitversion.yaml

  deployer-image:
    needs: version
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      name: deployer
      environment: ${{ inputs.environment || 'dev' }}
      version: ${{ needs.version.outputs.version }}
    secrets: inherit

  deploy:
    needs: deployer-image
    uses: ./.github/workflows/deploy-stage.yaml
    with:
      environment: ${{ inputs.environment || 'dev' }}
      version: ${{ needs.deployer-image.outputs.version }}
    secrets: inherit
