name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build
    branches:
      - master
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy-stage.yaml
    with:
      stage: dev
      app: deployer
      project: CdkGoLambdas
      region: eu-central-1
      s3ArtifactsBucket: cdkgolambdas-dev-euc1-dep-artifactsbucket2aac5544-19uymdegdjdys
      ciRoleName: CdkGoLambdas-dev-euc1-deployer-Stat-CiRole5A6E8228-DBYWGBRV50Z4
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
