name: GitVersion

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.gitversion.outputs.version }}

jobs:
  gitversion:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
