name: Promote image

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      version:
        type: string
        required: true
      src_stage:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Prepare vars
      id: vars
      run: |
        echo "Preparing variables"
        src_ecr_registry=${{ secrets.src_aws_account_id }}.dkr.ecr.${{ secrets.aws_global_region }}.amazonaws.com
        dst_ecr_registry=${{ secrets.aws_account_id }}.dkr.ecr.${{ secrets.aws_global_region }}.amazonaws.com
        src_ecr_repo=${{ secrets.project }}-${{ inputs.src_stage }}-${{ inputs.name }}
        dst_ecr_repo=${{ secrets.project }}-${{ secrets.stage }}-${{ inputs.name }}
        echo "src_ecr_repo=${src_ecr_registry}/${src_ecr_repo,,}" >> $GITHUB_OUTPUT
        echo "dst_ecr_repo=${dst_ecr_registry}/${dst_ecr_repo,,}" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-region: ${{ secrets.aws_global_region }}
        role-session-name: ${{ secrets.project }}-${{ secrets.stage }}-promote
        role-to-assume: ${{ secrets.aws_ci_role_arn }}
        role-duration-seconds: 3600

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1.5.3
      with:
        registries: ${{ secrets.aws_account_id }},${{ secrets.src_aws_account_id }}

    - name: Pull container image from src stage
      id: pull-image
      run: |
        echo "Downloading deployer container image from src ECR"
        image=${{ steps.vars.outputs.src_ecr_repo }}:${{ inputs.version }}
        docker pull $image
        echo "src_image=${image}" >> $GITHUB_OUTPUT

    - name: Push container image to dst stage
      run: |
        echo "Uploading deployer container image to dst ECR"
        image=${{ steps.vars.outputs.dst_ecr_repo }}:${{ inputs.version }}
        docker tag ${{ steps.pull-image.outputs.src_image }} $image
        docker push $image
        echo "dst_image=${image}" >> $GITHUB_OUTPUT
