name: Release

on:
  workflow_dispatch:

jobs:
  version:
    uses: ./.github/workflows/gitversion.yaml

  dev-to-stg:
    needs: version
    uses: ./.github/workflows/promote-image.yaml
    with:
      name: deployer
      version: ${{ needs.version.outputs.version }}
      src_stage: dev
      environment: stg
    secrets: inherit

  stg-deploy:
    needs:
      - version
      - dev-to-stg
    uses: ./.github/workflows/deploy-stage.yaml
    with:
      environment: stg
      version: ${{ needs.version.outputs.version }}
    secrets: inherit

  stg-to-prd:
    needs:
      - version
      - stg-deploy
    uses: ./.github/workflows/promote-image.yaml
    with:
      name: deployer
      version: ${{ needs.version.outputs.version }}
      src_stage: stg
      environment: prd
    secrets: inherit

  prd-deploy:
    needs:
      - version
      - stg-to-prd
    uses: ./.github/workflows/deploy-stage.yaml
    with:
      environment: prd
      version: ${{ needs.version.outputs.version }}
    secrets: inherit
